### PR TITLE
Set the message view sortable.

### PR DESCRIPTION
**Pull request by RoySegall**
#79

### CODE REVIEW

**Comment by amitaibu** [comment]
Screenshot please :)

**Comment by RoySegall** [comment]
message___site-install

I had it ready for upload but forgot to attach it.

**Comment by amitaibu** [comment]
I don't think we need to make the message text sortable.

**Comment by amitaibu** [comment]
I'll tackle this

**Comment by amitaibu** [comment]
I've also added empty results page, and tackled the table's responsiveness

message___site-install

**Pull request merged**
