### PR TITLE
Rename messageType to messageTemplate

### PR DESCRIPTION
**Pull request by HelenaEksler**
#98

### CODE REVIEW

**Comment by HelenaEksler** [comment]
@RoySegall @amitaibu 
if `message_category` should not be changed to `message_group` - Ready for review.

**Comment by amitaibu** [comment]
needs a re-roll

**Comment by HelenaEksler** [comment]
@amitaibu Tests failed because of composer. Will re-start them later.

**Comment by HelenaEksler** [comment]
@amitaibu I've changed the drush version to 8 so travis now passing (https://github.com/Gizra/message/pull/102/files#diff-354f30a63fb0907d4ad57269548329e3R32)

**Comment by amitaibu** [comment]
Can you move the Travis fix to own PR please

**Comment by bojanz** [comment]
Let's do this! Needs a rebase first though.

**Comment by HelenaEksler** [comment]
@amitaibu I can't push to this any more.

**Comment by amitaibu** [comment]
Hi!

Now only Roy and myself have commit access to this repo. It would be great
if you could fork instead :)

**Comment by amitaibu** [comment]
Needs a re-roll

**Comment by jhedstrom** [comment]
I've rerolled in #112.

**Comment by amitaibu** [comment]
Closing in favor of #112

**Pull request closed without merging**
