### PR TITLE
Make message twig template discoverable

### PR DESCRIPTION
**Pull request by mccrodp**
Follow up to https://github.com/Gizra/message/issues/31

I think it needs something like this in D8 still from referring to node.module. However, I cannot verify that this is working as it's not getting discovered from my tests using the current state of Message UI module for D8.

### CODE REVIEW

**Comment by mccrodp** [comment]
I can verify that the template is now getting called as I have tested adding `{{ dump() }}` and can see the output.

The problem now is that the `content` variable is not populated correctly. Neither the fields are displayed (possibly due to https://github.com/Gizra/message/issues/36) nor the partials as `#markup` variable is empty due to the issue at https://github.com/Gizra/message/issues/35

**Comment by RoySegall** [comment]
The same goes for this one. The PR is huge. Can you create a new PR against the correct branch? 10x.

**Comment by mccrodp** [comment]
Will do, things got a bit messy for a while, I wasn't sure where to file PRs / merge to and from. I do now. 

So, I will create a new PR for this. However, https://github.com/Gizra/message/issues/35 and https://github.com/Gizra/message/issues/36 will still be an issue here for any modules that want to use the twig template; `content` variable is not set correctly.

**Comment by RoySegall** [comment]
OK. Closing this one. Waiting for the new PR.

**Pull request closed without merging**
