### PR TITLE
Update MessageType and MessageTypeInterface parent classes

### PR DESCRIPTION
**Pull request by mccrodp**
I seem to have closed https://github.com/Gizra/message/pull/33 when trying to clean up this pull request. So, here is the new one that does exactly that stated in https://github.com/Gizra/message/pull/33#issue-108335575 from commit **3cb623c** in September.

> [Changed Message Type to "extends ConfigEntityBundleBase implements MessageTypeInterface" and > changed MessageTypeInterface to extends ConfigEntityInterface]
> 
> Following NodeType class and NodeTypeInterface

### CODE REVIEW

**Comment by RoySegall** [comment]
@mccrodp The PR is kind of messy and not created against the corrent branch. What was the original purpose of this one?

**Comment by mccrodp** [comment]
@RoySegall - Yes it probably is. This PR comes from work during drupalcon on Message UI when these issues were found with Message: https://github.com/Gizra/message/issues/35 and https://github.com/Gizra/message/issues/36 

I don't think it solved this issues, but may help as these are the correct classes to extend.

It's late now for me, so I can create a (new?) cleaner PR for this tomorrow if that helps.

> [Changed Message Type to "extends ConfigEntityBundleBase implements MessageTypeInterface" and > changed MessageTypeInterface to extends ConfigEntityInterface]
> 
> Following NodeType class and NodeTypeInterface

**Comment by RoySegall** [comment]
I'm starting remember. Let me tackle this one after the first stable release. I would like to see the twig PR goes in.

**Comment by mccrodp** [comment]
Ok, I created a new twig PR: https://github.com/Gizra/message/pull/48

@RoySegall Yes, maybe best to look at https://github.com/Gizra/message/issues/35 and https://github.com/Gizra/message/issues/36 after first release, important to get message out there in the wild first :)

Should I create a new PR for this one though in the meantime? It's a simple correction and all lights are still green.

**Pull request closed without merging**
