### PR TITLE
Fixes Example module misses depencency on Comment module #170

### PR DESCRIPTION
**Pull request by Axolotlke**

### CODE REVIEW

**Comment by jhedstrom** [comment]
What are the errors if `comment` or `node` are not enabled? After a brief glance at the code, I didn't immediately see any hard dependencies. If there are config errors, then we should move the example configs from `config/install` to `config/optional`.

**Comment by jhedstrom** [comment]
Ah, nevermind, I see the error is in #170.

**Comment by amitaibu** [comment]
> What are the errors if comment or node are not enabled?

I think since it's an example module it makes sense to enable those dependencies, otherwise the dev might miss what the module will be tracking

**Comment by jhedstrom** [comment]
Yeah, that makes sense to me too.

**Comment by jhedstrom** [comment]
Thanks!

**Pull request merged**
