### PR TITLE
Update Travis CI.

### LINKED ISSUE #131: Copy travis settings from Gizra/og
We have some nice setup in https://github.com/Gizra/og for Travis, we can probably copy it and get nicer separation between tests and coder

### PR DESCRIPTION
**Pull request by jhedstrom**
- Fixes #131 

This PR is currently based off of the #136 branch.

### CODE REVIEW

**Comment by jhedstrom** [comment]
Assuming green, this and #136 are ready for review @amitaibu.

**Comment by amitaibu** [comment]
👍

**Comment by jhedstrom** [comment]
This had to be merged into 8.x. Good now.

**Comment by amitaibu** [comment]
Thanks :)

**Pull request merged**
