### PR TITLE
fix coder version

### PR DESCRIPTION
**Pull request by NewZeal**
Fix to require-dev on composer.json

### CODE REVIEW

**Comment by jhedstrom** [comment]
Build is failing with this message:

```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package drupal/coder ^2.0 exists as drupal/coder[7.2.2, 7.2.3, 7.2.4, 7.2.5, 8.2.0, 8.2.0-alpha1, 8.2.0-alpha2, 8.2.0-beta1, 8.2.0-rc1, 8.2.1, 8.2.10, 8.2.11, 8.2.12, 8.2.2, 8.2.3, 8.2.4, 8.2.5, 8.2.6, 8.2.7, 8.2.8, 8.2.9, dev-7.x-2.x, dev-8.x-2.x] but these are rejected by your constraint.
```

You might need to add drupal.org's composer repo to the `composer.json` file for the semantic versioning to work:

```json
  "repositories": [
    {
      "type": "composer",
      "url": "https://packages.drupal.org/8"
    },
```

**Comment by NewZeal** [comment]
This is the error message I get when trying to install the module 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/message_ui 1.x-dev requires drupal/coder ^8.2 -> no matching package found.
    - drupal/message_ui dev-1.x requires drupal/coder ^8.2 -> no matching package found.
    - drupal/message_ui 1.0.0-beta2 requires drupal/coder ^8.2 -> no matching package found.
    - drupal/message_ui 1.0.0-beta1 requires drupal/coder ^8.2 -> no matching package found.
```
Does require-dev not have the same version naming as require?

**Comment by NewZeal** [comment]
Is it necessary to have a requirement for coder module in a contrib module? On our system we are running codesniffer as part of the deploy system. By requiring coder here, we are not actually running it are we? It is not an actual module dependency. If it was it would be referenced in message.info.yml.

**Comment by jhedstrom** [comment]
> Is it necessary to have a requirement for coder module in a contrib module?

That's why it's specified as `require-dev`, rather than `require`. Composer will not pull in vendor `require-dev` dependencies, only the top-level `require-dev` libraries specified in your `composer.json`.

**Comment by NewZeal** [comment]
There is no need for this pull.  require-dev works as expected.  The problem is with message_ui using require rather than require-dev.  Closing this.

**Pull request closed without merging**
